[package]
name = "launcher-test-client"
version = "0.0.1"
authors = ["ustulation <ustulation@gmail.com>"]

[dependencies]
regex = "*"
byteorder = "*"
bufstream = "*"
sodiumoxide = "*"
rustc-serialize = "*"
