[package]
name = "launcher-test-client"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]

[dependencies]
regex = "*"
byteorder = "*"
bufstream = "*"
sodiumoxide = "*"
rustc-serialize = "*"
